// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfMBe5564dE53_uvQZBeEibovlVb_W1Ag',
    appId: '1:778878259492:web:d964cebcf785ce9dd4a3b1',
    messagingSenderId: '778878259492',
    projectId: 'flutter-firebase-5de90',
    authDomain: 'flutter-firebase-5de90.firebaseapp.com',
    storageBucket: 'flutter-firebase-5de90.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZpu0M5f9sYb4Pkz-j_9NSxL0L_Iegz1s',
    appId: '1:778878259492:android:8a2e625493ddc07dd4a3b1',
    messagingSenderId: '778878259492',
    projectId: 'flutter-firebase-5de90',
    storageBucket: 'flutter-firebase-5de90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHAE9EgYmZT0dOHbtcDS2k5wap295KJGc',
    appId: '1:778878259492:ios:712a3168c195dd3bd4a3b1',
    messagingSenderId: '778878259492',
    projectId: 'flutter-firebase-5de90',
    storageBucket: 'flutter-firebase-5de90.appspot.com',
    iosClientId: '778878259492-bitkmt8ns1rapijhf8i4h8gko9im0qv9.apps.googleusercontent.com',
    iosBundleId: 'com.codigocorrecto.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHAE9EgYmZT0dOHbtcDS2k5wap295KJGc',
    appId: '1:778878259492:ios:712a3168c195dd3bd4a3b1',
    messagingSenderId: '778878259492',
    projectId: 'flutter-firebase-5de90',
    storageBucket: 'flutter-firebase-5de90.appspot.com',
    iosClientId: '778878259492-bitkmt8ns1rapijhf8i4h8gko9im0qv9.apps.googleusercontent.com',
    iosBundleId: 'com.codigocorrecto.crud',
  );
}
